#!/bin/csh -f 
#PBS -j oe 
###PBS -m ae 
#PBS -V
#PBS -q regular
#PBS -N caseA
#PBS -A P00000000
#PBS -l select=1:ncpus=4:mpiprocs=4:ompthreads=1
#PBS -l walltime=00:15:00

#--------------------------------------------

cd /cluster/home/pduarte/pduarte8/CICE/caseA
source ./cice.settings || exit 2
source ./env.${ICE_MACHCOMP} || exit 2

echo " "
echo "${0}:"

set  stamp   = `date '+%y%m%d-%H%M%S'`
set ICE_RUNLOG_FILE = "cice.runlog.${stamp}"

#--------------------------------------------

./setup_run_dirs.csh

#--------------------------------------------
cd ${ICE_RUNDIR}

setenv OMP_NUM_THREADS 1

cp -f ${ICE_CASEDIR}/ice_in ${ICE_RUNDIR}
set diagtype = `grep -i diag_type ${ICE_CASEDIR}/ice_in | grep -i stdout | wc -l`
set diagfile = `grep -i diag_file ${ICE_CASEDIR}/ice_in | sed -e "s/.* = '\(.*\)'/\1/"`

echo " "
echo "CICE case directory is ${ICE_CASEDIR}"
echo "CICE rundir is ${ICE_RUNDIR}"
echo "CICE log file is ${ICE_RUNLOG_FILE}"
echo "CICE run started : `date`"

mpiexec_mpt -np 4 omplace ./cice >&! $ICE_RUNLOG_FILE
echo "CICE run finished: `date`"
echo " "

#--------------------------------------------

if !(-d ${ICE_LOGDIR}) mkdir -p ${ICE_LOGDIR}

set checkfile = ${ICE_RUNLOG_FILE}
cp -p ${ICE_RUNLOG_FILE} ${ICE_LOGDIR}
echo "CICE output file is ${ICE_LOGDIR}/${ICE_RUNLOG_FILE}"
echo "`date` ${0}: CICE output file is ${ICE_LOGDIR}/${ICE_RUNLOG_FILE}" >> ${ICE_CASEDIR}/README.case

if ( ${diagtype} == 0) then
  set checkfile = ${diagfile}
  cp -p ${diagfile} ${ICE_LOGDIR}
  echo "CICE output file is ${ICE_LOGDIR}/${diagfile}"
  echo "`date` ${0}: CICE output file is ${ICE_LOGDIR}/${diagfile}" >> ${ICE_CASEDIR}/README.case
endif

grep ' CICE COMPLETED SUCCESSFULLY' ${checkfile}
if ( $status == 0 ) then
  echo "CICE run completed successfully"
  echo "`date` ${0}: CICE run completed successfully"  >> ${ICE_CASEDIR}/README.case
else
  echo "CICE run did NOT complete"
  echo "`date` ${0}: CICE run did NOT complete"  >> ${ICE_CASEDIR}/README.case
  exit -1
endif

if ( ${diagtype} == 0) then
  exit -1
endif

echo "done ${0}"

